InvoiceManager/ViewModels/Invoice.cs
using System;
using System.Collections.Generic;

namespace InvoiceManager.ViewModels
{
    public class InvoiceViewModel : Invoice
    {
        //public int id;
        //public int clientId;
        //public DateTime invoiceDate;
        public List<ItemViewModel> items = new List<ItemViewModel>();

        public InvoiceViewModel(int clientId, DateTime invoiceDate)
        {
            this.clientId = clientId;
            this.invoiceDate = invoiceDate;
        }

        public InvoiceViewModel(int id, int clientId, DateTime invoiceDate)
        {
            this.id = id;
            this.clientId = clientId;
            this.invoiceDate = invoiceDate;
        }
    }

}

InvoiceManager/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InvoiceManager;

namespace InvoiceManager.Controllers
{
    public class InvoicesController : Controller
    {
        private InvoiceEntities1 db = new InvoiceEntities1();

        // GET: Invoices
        public ActionResult Index()
        {
            IQueryable<Invoice> invoices = db.Invoices.Include(i => i.Client);
            return View(invoices.ToList());
        }

        // GET: Invoices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // GET: Invoices/Create
        public ActionResult Create()
        {
            ViewBag.clientId = new SelectList(db.Clients, "id", "fullName");
            return View();
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,clientId,invoiceDate")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Invoices.Add(invoice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.clientId = new SelectList(db.Clients, "id", "fullName", invoice.clientId);
            return View(invoice);
        }

        // GET: Invoices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            ViewBag.clientId = new SelectList(db.Clients, "id", "fullName", invoice.clientId);
            return View(invoice);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,clientId,invoiceDate")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.clientId = new SelectList(db.Clients, "id", "fullName", invoice.clientId);
            return View(invoice);
        }

        // GET: Invoices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = db.Invoices.Find(id);
            db.Invoices.Remove(invoice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InvoiceManager/Views/Invoices/Create.cshtml
@model InvoiceManager.Invoice

@{
    ViewBag.Title = "Create";
}


<h2 style="text-align: center">CREATE NEW INVOICE</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.clientId, "Client Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("clientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.clientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.invoiceDate, "Invoice Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.invoiceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.invoiceDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<h4 style="color: black; text-align: center; font-weight: bold">Add Invoice Items</h4>

<div class="add-item">
    <label for="item">Item</label>
    <input class="form-control" type="text" id="itemName" name="item" required><br>

    <label for="unitPrice">Unit Price</label>
    <input class="form-control" type="text" id="unitPrice" name="unitPrice" required><br>

    <label for="quantity">Quantity</label>
    <input class="form-control" type="text" id="quantity" name="quantity" value="1"><br>

    <button class="btn" id="add-item" onclick="addItem()">Add Item</button>
</div>

<h4 style="color: black; text-align: center; font-weight: bold">Items</h4>

<div class="items">
    <table>
        <thead>
            <tr>
                <th>Item Name</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Total Price</th>
            </tr>
        </thead>

        <tbody id="items">
            
        </tbody>
    </table>

</div>


<script>
    let tableBody = document.getElementById("items");

    function addItem() {
        let itemName = document.getElementById("itemName").value;
        let unitPrice = document.getElementById("unitPrice").value;
        let quantity = document.getElementById("quantity").value;

        let newRow = document.createElement("tr");

        newRow.innerHTML = `
            <tr>
                <td class="r1">${itemName}</td>
                <td class="r2">${unitPrice} EGP</td>
                <td class="r3">${quantity}</td>
                <td class="r4">${unitPrice * quantity} EGP</td>
            </tr>
        `;

        tableBody.appendChild(newRow);

    }
</script>



<div>
    @Html.ActionLink("Back", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}




<style>
    .form-control, .text-danger {
        width: 100%;
        border-radius: 10px
    }

    h5 {
        font-weight: bold;
        display: inline-flex
    }



    .btn {
        width: 100%;
        border-radius: 60px;
        margin: 0;
        background-color: #099;
        color: white;
        font-weight: bold
    }

        .btn:hover {
            background-color: #055;
            color: white;
        }

    #add-item {
        width: 24%
    }
    .add-item .label {
        width: 100px
    }

    .form-horizontal {
        background-color: #eee;
        padding: 0 0 15px 0;
        border-radius: 20px;
        margin-bottom: 20px
    }

    .add-item {
        width: 100%;
        background-color: #eee;
        padding: 20px;
        border-radius: 20px;

    }


    table, td, th {
        border: 1px solid black;
        padding: 5px;
        margin: 2px
    }

    td, th {
        padding: 5px 40px;
    }

    table {
        margin-left: 23%;
        margin-top: 20px;
    }
    
</style>

InvoiceManager/Views/Invoices/Delete.cshtml
@model InvoiceManager.Invoice

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.invoiceDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.invoiceDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Client.fullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.fullName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

InvoiceManager/Views/Invoices/Details.cshtml
@model InvoiceManager.Invoice

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.invoiceDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.invoiceDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Client.fullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.fullName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

InvoiceManager/Views/Invoices/Edit.cshtml
@model InvoiceManager.Invoice

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.clientId, "clientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("clientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.clientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.invoiceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.invoiceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.invoiceDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InvoiceManager/Views/Invoices/Index.cshtml
@model IEnumerable<InvoiceManager.Invoice>

@{
    ViewBag.Title = "Index";
}

<h2 style="text-align: center; font-weight: bold">INVOICES</h2>


<table class="table">
    <tr>
        <th>
            Invoice Date
        </th>
        <th>
            Client Name
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.invoiceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Client.fullName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>


<button onclick="window.location.href = '@Url.Action("Create", "Invoices", new {})'" class="add-invoice">
    Create New Invoice
</button>


<style>
    .add-invoice {
        width: 50%;
        border-radius: 60px;
        margin: 10px 25%;
    }

    button {
        background-color: #099;
        color: white;
        transform: scale(1);
        transition: transform 1s;
    }

        button:hover {
            transform: scale(1.1);
            transition: transform 1s;
        }
</style>